package com.example.dao;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class UserDAO{
    private static final String DB_URL = "jdbc:h2:~/patients";
    private static final String DB_USERNAME = "sa";
    private static final String DB_PASSWORD = "";
    private static final String TABLE = "users";
    private Connection connection;

    public UserDAO() throws IOException {
        try {
            Class.forName("org.h2.Driver");

            connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD);

            createTableIfNotExists();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    public void createTableIfNotExists() throws SQLException {
        String sql = "CREATE TABLE IF NOT EXISTS " + TABLE + " (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(256) NOT NULL UNIQUE, password VARCHAR(60) NOT NULL, role VARCHAR(10) NOT NULL);";
        Statement statement = connection.createStatement();

        statement.executeUpdate(sql);
    }
}
